name: Deno
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  info:
    runs-on: ubuntu-20.04
    steps:
      - name: Github JSON event
        run: echo "${{ toJson(github.event) }}"

  deno:
    runs-on: ubuntu-20.04
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run deno script
        run: scripts/ci-deno.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
