name: Deno
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  info:
    runs-on: ubuntu-20.04
    steps:
      - name: Info
        run: |
          echo CONTEXT = ${{ github.context }}
          echo EVENT = "${{ toJson(github.event) }}"
          echo NUMBER = ${{ github.event.issue.number }}

  deno:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run deno script
        if: github.ref != 'refs/heads/main'
        run: scripts/ci-deno.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
