name: Deno
on:
  push:

jobs:
  deno:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Info
        run: |
          echo CONTEXT = ${{ github.context }}
          echo EVENT = ${{ toJson(github.event) }}
          echo NUMBER = ${{ github.event.issue.number }}

      - name: Run deno script
        run: scripts/ci-deno.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
